-- Sprint 6.1.3: professional exercise coverage expansion by muscle group.
-- Safe migration: no deletes, no existing id changes, no media without license.
-- This supersedes the unapplied Sprint 6.1.2 migration. If 6.1.2 was not applied,
-- apply this migration after Sprint 6 and Sprint 6.1.

ALTER TABLE public.exercises
  ADD COLUMN IF NOT EXISTS instrucciones text[] NOT NULL DEFAULT '{}'::text[];

ALTER TABLE public.exercises
  ADD COLUMN IF NOT EXISTS aliases text[] NOT NULL DEFAULT '{}'::text[];

ALTER TABLE public.exercises
  DROP CONSTRAINT IF EXISTS exercises_estado_calidad_check;

ALTER TABLE public.exercises
  ADD CONSTRAINT exercises_estado_calidad_check
  CHECK (estado_calidad IN ('legacy', 'pendiente', 'basico', 'revisar', 'curado', 'deprecado', 'premium'));

CREATE TEMP TABLE sprint613_exercise_catalog (
  id text PRIMARY KEY,
  existed_before boolean NOT NULL DEFAULT false,
  action text NOT NULL,
  nombre text NOT NULL,
  aliases text[] NOT NULL,
  nivel text NOT NULL,
  nivel_minimo text NOT NULL,
  grupo_muscular text NOT NULL,
  musculo_principal text NOT NULL,
  musculos_secundarios text[] NOT NULL,
  equipamiento text NOT NULL,
  equipo_requerido text[] NOT NULL,
  lugar text NOT NULL,
  objetivo text NOT NULL,
  tipo_entrenamiento text NOT NULL,
  patron_movimiento text NOT NULL,
  descripcion text NOT NULL,
  instrucciones text[] NOT NULL,
  cues_tecnicos text[] NOT NULL,
  errores_comunes text[] NOT NULL,
  contraindicaciones text[] NOT NULL,
  sustituciones text[] NOT NULL,
  progresiones text[] NOT NULL,
  regresiones text[] NOT NULL,
  series_sugeridas integer,
  repeticiones_sugeridas integer,
  rango_reps_min integer,
  rango_reps_max integer,
  descanso_segundos_min integer,
  descanso_segundos_max integer,
  rir_recomendado integer,
  duracion_promedio_segundos integer,
  estado_calidad text NOT NULL DEFAULT 'curado',
  not_added_reason text
) ON COMMIT DROP;

INSERT INTO sprint613_exercise_catalog (
  id, existed_before, action, nombre, aliases, nivel, nivel_minimo, grupo_muscular,
  musculo_principal, musculos_secundarios, equipamiento, equipo_requerido, lugar,
  objetivo, tipo_entrenamiento, patron_movimiento, descripcion, instrucciones,
  cues_tecnicos, errores_comunes, contraindicaciones, sustituciones, progresiones,
  regresiones, series_sugeridas, repeticiones_sugeridas, rango_reps_min, rango_reps_max,
  descanso_segundos_min, descanso_segundos_max, rir_recomendado, duracion_promedio_segundos,
  estado_calidad, not_added_reason
)
VALUES
-- Existing rows corrected or made more specific.
('16', true, 'improved_existing', 'Peso muerto rumano con mancuernas', ARRAY['dumbbell romanian deadlift','dumbbell rdl','RDL con mancuernas'], 'principiante', 'principiante', 'piernas', 'isquiosurales', ARRAY['gluteo mayor','erectores espinales','antebrazos'], 'mancuernas', ARRAY['mancuernas'], 'cualquiera', 'hipertrofia', 'fuerza', 'bisagra de cadera', 'Bisagra de cadera con mancuernas para desarrollar isquiosurales y gluteos con una carga facil de controlar. Es util para aprender el patron antes de pasar a barra.', ARRAY['Sostén las mancuernas frente a los muslos','Flexiona ligeramente rodillas y lleva la cadera hacia atras','Baja las mancuernas cerca de las piernas hasta sentir tension posterior','Mantén columna neutra y abdomen activo','Sube extendiendo cadera sin arquear la espalda'], ARRAY['Cadera hacia atras','Carga cerca del cuerpo','Espalda neutra','Sube con gluteos'], ARRAY['Redondear espalda','Convertirlo en sentadilla','Alejar las mancuernas','Bajar mas alla del rango controlable'], ARRAY['Evitar si provoca dolor agudo lumbar o en isquiosurales','Reducir rango si se pierde columna neutra'], ARRAY['Peso muerto rumano con barra','Peso muerto rumano a una pierna con mancuerna','Hip thrust con barra'], ARRAY['Aumentar carga gradualmente','Usar pausa abajo','Pasar a barra si la tecnica es estable'], ARRAY['Bisagra con palo','Puente de gluteo','Rango parcial controlado'], 3, 10, 8, 12, 90, 150, 2, NULL, 'curado', NULL),
('39', true, 'converted_variant', 'Peso muerto rumano con barra', ARRAY['barbell romanian deadlift','barbell rdl','RDL con barra'], 'intermedio', 'intermedio', 'piernas', 'isquiosurales', ARRAY['gluteo mayor','erectores espinales','antebrazos'], 'barra, discos', ARRAY['barra','discos'], 'gimnasio', 'hipertrofia', 'fuerza', 'bisagra de cadera', 'Bisagra de cadera con barra enfocada en isquiosurales y gluteos. Permite progresar carga de forma precisa y requiere mayor control tecnico que la version con mancuernas.', ARRAY['Toma la barra frente a los muslos','Activa abdomen y coloca pies al ancho de cadera','Lleva la cadera hacia atras manteniendo la barra pegada al cuerpo','Baja hasta tension controlada en isquiosurales','Sube extendiendo cadera sin hiperextender espalda'], ARRAY['Barra pegada al cuerpo','Rodillas semiflexionadas','Cadera atras','Cuello neutral'], ARRAY['Alejar la barra','Redondear espalda','Doblar demasiado rodillas','Buscar profundidad sin control'], ARRAY['Evitar si provoca dolor lumbar agudo','Usar mancuernas si no puedes mantener la barra cerca'], ARRAY['Peso muerto rumano con mancuernas','Peso muerto convencional con barra','Hip thrust con barra'], ARRAY['Aumentar carga','Usar tempo lento','Usar pausa bajo rodilla'], ARRAY['Peso muerto rumano con mancuernas','Bisagra con palo','Rango parcial'], 3, 8, 6, 10, 120, 180, 2, NULL, 'curado', NULL),
('23', true, 'improved_existing', 'Remo con mancuerna a una mano', ARRAY['one-arm dumbbell row','remo unilateral con mancuerna'], 'principiante', 'principiante', 'espalda', 'dorsal ancho', ARRAY['romboides','trapecio medio','biceps','core'], 'mancuerna, banco', ARRAY['mancuerna','banco'], 'cualquiera', 'hipertrofia', 'fuerza', 'jalon horizontal unilateral', 'Remo unilateral que permite trabajar dorsal ancho y espalda media con buen rango. Tambien ayuda a corregir diferencias entre lados.', ARRAY['Apoya una mano y una rodilla sobre el banco','Mantén espalda neutra y mancuerna bajo el hombro','Jala el codo hacia la cadera','Pausa sin girar el torso','Baja con control hasta estirar la espalda'], ARRAY['Codo hacia la cadera','Torso estable','Hombro lejos de la oreja','Controla el regreso'], ARRAY['Girar demasiado el torso','Encoger hombro','Jalar solo con biceps','Rebotar la mancuerna'], ARRAY['Evitar si genera dolor de hombro o espalda baja','Reducir carga si no puedes estabilizar el tronco'], ARRAY['Remo en polea sentado','Remo pecho apoyado','Remo con barra inclinado'], ARRAY['Aumentar carga','Pausar arriba','Usar banco inclinado pecho apoyado'], ARRAY['Remo con banda','Remo en polea ligera','Rango parcial'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('35', true, 'renamed_existing', 'Remo con barra inclinado', ARRAY['barbell row','bent-over row','remo con barra'], 'intermedio', 'intermedio', 'espalda', 'espalda media', ARRAY['dorsal ancho','romboides','trapecio medio','deltoides posterior','biceps','erectores espinales'], 'barra, discos', ARRAY['barra','discos'], 'gimnasio', 'fuerza', 'fuerza', 'jalon horizontal', 'Remo pesado de espalda con barra que desarrolla dorsal, espalda media y estabilidad de cadena posterior. Es una variante basica para fuerza e hipertrofia.', ARRAY['Toma la barra con agarre firme','Inclina el torso manteniendo espalda neutra','Jala la barra hacia el abdomen o parte baja del pecho','Junta escapulas sin encoger hombros','Baja con control sin perder la posicion'], ARRAY['Torso firme','Barra cerca del cuerpo','Codos hacia atras','Cuello neutral'], ARRAY['Redondear la espalda','Usar impulso de cadera','Encoger hombros','Recortar el rango'], ARRAY['Evitar si provoca dolor lumbar agudo','Usar remo pecho apoyado si cuesta estabilizar el torso'], ARRAY['Remo en polea sentado','Remo en T','Remo pecho apoyado'], ARRAY['Aumentar carga','Usar pausa arriba','Usar agarre mas estricto'], ARRAY['Remo pecho apoyado','Remo con mancuerna a una mano','Remo en polea sentado'], 4, 8, 6, 10, 120, 180, 2, NULL, 'curado', NULL),
('49', true, 'renamed_existing', 'Remo en polea sentado', ARRAY['remo en polea baja','seated cable row','seated row','cable row'], 'principiante', 'principiante', 'espalda', 'espalda media', ARRAY['dorsal ancho','romboides','trapecio medio','deltoides posterior','biceps'], 'polea baja, agarre', ARRAY['polea baja','agarre'], 'gimnasio', 'hipertrofia', 'fuerza', 'jalon horizontal', 'Remo de espalda en polea baja con tension continua. Es una variante estable para entrenar espalda media y dorsal con menor demanda lumbar.', ARRAY['Ajusta el peso y conecta el agarre','Siéntate con espalda neutra y pies firmes','Inicia con brazos extendidos sin redondear la espalda','Tira del agarre hacia el abdomen','Retrae escapulas al final del movimiento','Regresa con control sin balancear el torso'], ARRAY['Pecho abierto','Codos cerca del cuerpo','Escapulas hacia atras','Regreso controlado'], ARRAY['Balancear el torso','Redondear espalda','Jalar solo con brazos','Encoger hombros'], ARRAY['Evitar si causa dolor agudo de hombro o espalda baja','Reducir carga si pierdes postura'], ARRAY['Remo con mancuerna a una mano','Remo pecho apoyado','Remo con barra inclinado'], ARRAY['Aumentar carga','Pausar con escapulas retraidas','Usar agarre mas amplio'], ARRAY['Reducir carga','Usar agarre neutral','Remo con banda'], 3, 10, 8, 15, 60, 120, 2, NULL, 'curado', NULL),
('74', true, 'renamed_existing', 'Remo ergómetro', ARRAY['rowing machine','remo indoor','máquina de remo cardiovascular','ergómetro'], 'principiante', 'principiante', 'cardio', 'sistema cardiovascular', ARRAY['dorsal ancho','piernas','gluteos','core'], 'remo ergómetro', ARRAY['remo ergómetro'], 'gimnasio', 'cardio', 'cardio', 'locomocion/cardio', 'Ejercicio cardiovascular en remo ergómetro que combina piernas, cadera, espalda y brazos. Se programa por tiempo o intervalos y no sustituye a los remos de fuerza para espalda.', ARRAY['Ajusta los soportes de pies','Inicia con rodillas flexionadas y espalda larga','Empuja con piernas, extiende cadera y luego jala el mango','Regresa brazos, tronco y piernas en orden controlado','Mantén ritmo sostenible y baja intensidad al terminar'], ARRAY['Piernas primero','Tronco firme','Jala al final','Ritmo constante'], ARRAY['Jalar solo con brazos','Redondear espalda baja','Subir hombros','Acelerar perdiendo coordinacion'], ARRAY['Detener si hay mareo, dolor toracico o falta de aire inusual','Reducir intensidad si aparece dolor lumbar'], ARRAY['Elíptica','Ciclismo','Saltar cuerda','Sprints'], ARRAY['Aumentar duracion','Agregar intervalos','Subir resistencia gradualmente'], ARRAY['Reducir duracion','Bajar resistencia','Usar ritmo continuo suave'], NULL, NULL, NULL, NULL, 60, 120, NULL, 1200, 'curado', NULL),
('45', true, 'improved_existing', 'Curl de bíceps con barra', ARRAY['barbell curl','ez bar curl','curl con barra EZ'], 'intermedio', 'principiante', 'brazos', 'biceps braquial', ARRAY['braquial','braquiorradial','antebrazo'], 'barra recta o barra EZ', ARRAY['barra recta o barra EZ'], 'gimnasio', 'hipertrofia', 'fuerza', 'curl de codo', 'Curl bilateral con barra para trabajar biceps con carga progresiva. Es una variante base para fuerza e hipertrofia del brazo.', ARRAY['Sujeta la barra con agarre supino','Mantén codos cerca del torso','Flexiona codos sin balancear el cuerpo','Aprieta arriba sin adelantar hombros','Baja con control hasta extender brazos'], ARRAY['Codos estables','Muñecas neutrales','Torso quieto','Bajada controlada'], ARRAY['Balancear el torso','Adelantar codos','Flexionar muñecas','Usar carga excesiva'], ARRAY['Evitar si causa dolor de muñeca o codo','Usar barra EZ o mancuernas si molesta la muñeca'], ARRAY['Curl de bíceps con mancuernas','Curl martillo con mancuernas','Curl en polea baja'], ARRAY['Aumentar carga','Pausar arriba','Usar tempo lento'], ARRAY['Curl con mancuernas alterno','Curl en polea ligera','Reducir rango temporalmente'], 3, 10, 8, 12, 60, 90, 2, NULL, 'curado', NULL),
('9', true, 'improved_existing', 'Curl martillo con mancuernas', ARRAY['hammer curl','dumbbell hammer curl'], 'principiante', 'principiante', 'brazos', 'braquial', ARRAY['braquiorradial','biceps braquial','antebrazo'], 'mancuernas', ARRAY['mancuernas'], 'cualquiera', 'hipertrofia', 'fuerza', 'curl de codo agarre neutro', 'Curl con agarre neutro que enfatiza braquial y braquiorradial. Complementa el curl supino y ayuda al desarrollo visual del brazo y antebrazo.', ARRAY['Sujeta mancuernas con palmas enfrentadas','Mantén codos pegados al torso','Sube sin girar las muñecas','Pausa brevemente arriba','Baja lento hasta extender brazos'], ARRAY['Agarre neutro','Codos quietos','No balancees','Controla la bajada'], ARRAY['Balancear hombros','Convertirlo en curl supino','Subir demasiado rapido','Perder control abajo'], ARRAY['Reducir carga si molesta codo o muñeca'], ARRAY['Curl de bíceps con mancuernas','Curl de bíceps con barra','Curl invertido con barra'], ARRAY['Aumentar carga','Alternar brazos con control','Usar tempo lento'], ARRAY['Curl martillo alterno ligero','Curl en polea con cuerda'], 3, 12, 10, 15, 45, 90, 2, NULL, 'curado', NULL),
('10', true, 'renamed_existing', 'Extensión de tríceps por encima de la cabeza con mancuerna', ARRAY['overhead triceps extension','extension por encima de la cabeza','extension de triceps overhead'], 'principiante', 'principiante', 'brazos', 'triceps cabeza larga', ARRAY['triceps lateral','triceps medial','core'], 'mancuerna', ARRAY['mancuerna'], 'cualquiera', 'hipertrofia', 'fuerza', 'extension de codo overhead', 'Aislamiento de triceps por encima de la cabeza con mayor enfasis en la cabeza larga por la posicion del hombro.', ARRAY['Sostén la mancuerna con ambas manos','Coloca codos apuntando hacia arriba','Baja la mancuerna detras de la cabeza con control','Extiende codos sin abrirlos en exceso','Mantén abdomen activo y evita arquear espalda'], ARRAY['Codos al frente','Costillas abajo','Movimiento desde codo','Rango controlado'], ARRAY['Abrir demasiado codos','Arquear espalda','Mover hombros en exceso','Bajar sin control'], ARRAY['Evitar si provoca dolor de hombro o codo','Usar polea o menor rango si molesta'], ARRAY['Pushdown de tríceps en polea','Press francés con barra','Patada de tríceps con mancuernas'], ARRAY['Aumentar carga','Usar polea para tension continua','Pausar abajo'], ARRAY['Usar mancuerna mas ligera','Pushdown en polea','Reducir rango'], 3, 12, 10, 15, 60, 90, 2, NULL, 'curado', NULL),
('47', true, 'improved_existing', 'Press francés con barra', ARRAY['skull crusher','french press','extension de triceps acostado'], 'intermedio', 'intermedio', 'brazos', 'triceps cabeza larga', ARRAY['triceps lateral','triceps medial'], 'barra EZ o recta, banco', ARRAY['barra EZ o recta','banco'], 'gimnasio', 'hipertrofia', 'fuerza', 'extension de codo acostado', 'Extension de triceps acostado con barra, util para hipertrofia del triceps y progresion de fuerza en empujes.', ARRAY['Acuestate en banco con barra sobre hombros','Inclina ligeramente brazos hacia atras','Flexiona codos bajando la barra cerca de la frente','Extiende codos sin mover hombros','Controla la bajada en cada repeticion'], ARRAY['Codos fijos','Barra controlada','Muñecas neutras','No abras codos'], ARRAY['Mover hombros','Bajar sin control','Abrir codos','Usar peso excesivo'], ARRAY['Evitar si genera dolor de codo','Usar mancuernas o polea si molesta muñeca'], ARRAY['Pushdown de tríceps en polea','Extensión de tríceps por encima de la cabeza con mancuerna','Fondos en banco para tríceps'], ARRAY['Aumentar carga','Usar pausa abajo','Probar barra EZ'], ARRAY['Pushdown ligero','Extensión con mancuerna','Reducir rango'], 3, 10, 8, 12, 60, 90, 2, NULL, 'curado', NULL),
('3', true, 'improved_existing', 'Aperturas con mancuernas', ARRAY['dumbbell fly','aperturas plano','aperturas con mancuernas en banco'], 'principiante', 'principiante', 'pecho', 'pectoral mayor', ARRAY['deltoides anterior','serrato anterior'], 'mancuernas, banco', ARRAY['mancuernas','banco'], 'cualquiera', 'hipertrofia', 'fuerza', 'apertura horizontal', 'Ejercicio de aislamiento para pectoral que enfatiza estiramiento y control. Es complementario a los presses, no un reemplazo de fuerza pesada.', ARRAY['Acuestate con mancuernas sobre el pecho','Mantén codos ligeramente flexionados','Abre brazos en arco hasta sentir estiramiento controlado','Cierra llevando las mancuernas sobre el pecho','No choques las mancuernas arriba'], ARRAY['Codos suaves','Rango controlado','Pecho abierto','No rebotes abajo'], ARRAY['Bajar demasiado','Convertirlo en press','Usar peso excesivo','Perder control de hombros'], ARRAY['Evitar si provoca dolor anterior de hombro','Usar cable fly si se necesita tension continua'], ARRAY['Aperturas en polea','Press de banca con mancuernas','Lagartijas'], ARRAY['Aumentar control del tempo','Usar banco inclinado','Pasar a polea'], ARRAY['Cable fly ligero','Press con mancuernas liviano'], 3, 12, 10, 15, 60, 90, 2, NULL, 'curado', NULL),
('32', true, 'improved_existing', 'Press inclinado con barra', ARRAY['incline bench press','incline barbell press'], 'intermedio', 'intermedio', 'pecho', 'pectoral superior', ARRAY['deltoides anterior','triceps'], 'barra, banco inclinado, discos', ARRAY['barra','banco inclinado','discos'], 'gimnasio', 'hipertrofia', 'fuerza', 'empuje horizontal inclinado', 'Press con barra en banco inclinado para enfatizar pectoral superior y deltoides anterior. Es util como variante principal de pecho superior.', ARRAY['Ajusta el banco a inclinacion moderada','Retrae escapulas y apoya pies firmes','Baja la barra hacia la parte alta del pecho','Empuja en linea controlada','Evita perder contacto con el banco'], ARRAY['Escapulas firmes','Codos bajo control','No exageres inclinacion','Pies firmes'], ARRAY['Bajar al cuello','Abrir demasiado codos','Arquear espalda en exceso','Usar rango corto'], ARRAY['Evitar si causa dolor de hombro','Usar mancuernas si la barra molesta'], ARRAY['Press inclinado con mancuernas','Press de banca con barra','Press en máquina de pecho'], ARRAY['Aumentar carga','Pausa en pecho','Tempo lento'], ARRAY['Press inclinado con mancuernas ligero','Lagartijas inclinadas'], 4, 8, 6, 10, 120, 180, 2, NULL, 'curado', NULL),
('34', true, 'improved_existing', 'Press militar con barra', ARRAY['military press','barbell overhead press'], 'intermedio', 'intermedio', 'hombros', 'deltoides anterior', ARRAY['deltoides lateral','triceps','trapecio superior','core'], 'barra, discos', ARRAY['barra','discos'], 'gimnasio', 'fuerza', 'fuerza', 'empuje vertical', 'Press vertical con barra para fuerza de hombro y triceps. Requiere buena estabilidad de core y control de la trayectoria.', ARRAY['Coloca la barra a la altura de hombros','Toma agarre apenas mas ancho que hombros','Activa abdomen y gluteos','Empuja la barra verticalmente pasando cerca de la cara','Baja con control al punto inicial'], ARRAY['Costillas abajo','Barra cerca','Gluteos activos','No hiperextiendas espalda'], ARRAY['Arquear zona lumbar','Empujar la barra hacia adelante','Encoger cuello','Usar impulso excesivo'], ARRAY['Evitar si provoca dolor de hombro','Usar mancuernas o landmine press si hay molestia'], ARRAY['Press de hombro con mancuernas','Arnold press','Landmine press'], ARRAY['Aumentar carga','Pausa abajo','Press estricto'], ARRAY['Press sentado con mancuernas','Landmine press','Reducir carga'], 4, 8, 6, 10, 120, 180, 2, NULL, 'curado', NULL),
('42', true, 'improved_existing', 'Prensa de piernas', ARRAY['leg press'], 'principiante', 'principiante', 'piernas', 'cuadriceps', ARRAY['gluteo mayor','isquiosurales','aductores'], 'máquina de prensa', ARRAY['máquina de prensa'], 'gimnasio', 'hipertrofia', 'fuerza', 'sentadilla en máquina', 'Ejercicio de maquina para entrenar cuadriceps con estabilidad alta. Permite acumular volumen de piernas sin tanta demanda tecnica como una sentadilla libre.', ARRAY['Ajusta asiento y respaldo','Coloca pies firmes en la plataforma','Libera seguros y baja con control','Mantén rodillas alineadas con pies','Empuja sin bloquear rodillas con golpe'], ARRAY['Espalda apoyada','Rodillas alineadas','Rango controlado','No bloquees rodillas'], ARRAY['Despegar cadera','Juntar rodillas','Bloquear rodillas fuerte','Usar rango muy corto'], ARRAY['Evitar si provoca dolor agudo de rodilla o cadera','Ajustar pies y rango si hay molestia'], ARRAY['Sentadilla goblet','Sentadilla con barra','Zancadas con mancuernas'], ARRAY['Aumentar carga','Aumentar rango controlado','Usar tempo lento'], ARRAY['Sentadilla goblet','Step-up','Rango parcial controlado'], 4, 12, 10, 15, 90, 150, 2, NULL, 'curado', NULL),
('44', true, 'renamed_existing', 'Curl femoral en máquina', ARRAY['leg curl','hamstring curl','curl femoral'], 'principiante', 'principiante', 'piernas', 'isquiosurales', ARRAY['gastrocnemio'], 'máquina de curl femoral', ARRAY['máquina de curl femoral'], 'gimnasio', 'hipertrofia', 'fuerza', 'flexion de rodilla', 'Ejercicio de aislamiento para isquiosurales mediante flexion de rodilla. Complementa bisagras como peso muerto rumano.', ARRAY['Ajusta la maquina al largo de tus piernas','Fija cadera y torso contra el soporte','Flexiona rodillas llevando el rodillo hacia ti','Pausa brevemente en contraccion','Regresa lento sin perder tension'], ARRAY['Cadera fija','Controla abajo','No rebotes','Rango completo'], ARRAY['Levantar cadera','Usar impulso','Soltar la carga abajo','Recortar rango'], ARRAY['Evitar si causa dolor posterior de rodilla','Reducir carga si hay calambre'], ARRAY['Peso muerto rumano con mancuernas','Curl femoral con pelota','Peso muerto rumano con barra'], ARRAY['Aumentar carga','Pausar en contraccion','Tempo lento'], ARRAY['Curl femoral con pelota','Peso muerto rumano ligero'], 3, 12, 10, 15, 60, 90, 2, NULL, 'curado', NULL),
('15', true, 'renamed_existing', 'Elevación de talones de pie con mancuernas', ARRAY['standing calf raise','calf raise de pie'], 'principiante', 'principiante', 'piernas', 'gastrocnemio', ARRAY['soleo','estabilizadores de tobillo'], 'mancuernas', ARRAY['mancuernas'], 'cualquiera', 'hipertrofia', 'fuerza', 'flexion plantar de pie', 'Elevacion de talones de pie para pantorrilla con enfasis en gastrocnemio. Puede realizarse con mancuernas, maquina o peso corporal.', ARRAY['Sostén mancuernas a los lados','Apoya la parte delantera del pie de forma estable','Sube talones hasta contraer pantorrilla','Pausa arriba sin perder equilibrio','Baja lento hasta sentir estiramiento controlado'], ARRAY['Sube completo','Pausa arriba','Baja lento','Rodillas extendidas pero suaves'], ARRAY['Rebotar','Hacer rango corto','Perder equilibrio','Doblar demasiado rodillas'], ARRAY['Evitar si hay dolor agudo de Aquiles o tobillo'], ARRAY['Elevación de talones sentado','Elevación de talones en escalón','Elevación de talones en máquina'], ARRAY['Aumentar carga','Usar escalon para mas rango','Pausar arriba'], ARRAY['Peso corporal','Apoyo en pared','Rango corto'], 4, 15, 12, 20, 45, 90, 2, NULL, 'curado', NULL),
('26', true, 'improved_existing', 'Crunch abdominal', ARRAY['crunch','abdominal crunch'], 'principiante', 'principiante', 'core', 'recto abdominal', ARRAY['oblicuos'], 'peso corporal', ARRAY['peso corporal'], 'cualquiera', 'general', 'core', 'flexion de tronco', 'Ejercicio basico de flexion de tronco para trabajar recto abdominal. Debe hacerse con control, sin jalar cuello ni usar impulso.', ARRAY['Acuestate boca arriba con rodillas flexionadas','Coloca manos suaves junto a cabeza o pecho','Exhala y eleva hombros del suelo','Contrae abdomen sin jalar cuello','Baja lento hasta el inicio'], ARRAY['Barbilla neutral','Costillas hacia pelvis','Movimiento corto y controlado','Exhala al subir'], ARRAY['Jalar el cuello','Subir con impulso','Arquear zona lumbar','Hacer repeticiones muy rapidas'], ARRAY['Evitar si provoca dolor cervical o lumbar','Usar dead bug si molesta la flexion'], ARRAY['Crunch en polea','Plancha abdominal','Dead bug'], ARRAY['Aumentar reps','Pausar arriba','Pasar a crunch en polea'], ARRAY['Dead bug','Plancha abdominal','Rango menor'], 3, 15, 12, 25, 30, 60, 2, NULL, 'curado', NULL),
('28', true, 'improved_existing', 'Bird dog', ARRAY['bird dog'], 'principiante', 'principiante', 'core', 'core', ARRAY['gluteo mayor','erectores espinales','hombros'], 'peso corporal', ARRAY['peso corporal'], 'cualquiera', 'general', 'core', 'anti-rotacion', 'Ejercicio de estabilidad lumbopelvica que entrena core, gluteos y control contralateral. Es util como base de control motor.', ARRAY['Colocate en cuatro puntos','Activa abdomen sin arquear espalda','Extiende brazo y pierna contraria','Pausa manteniendo pelvis estable','Regresa lento y alterna lados'], ARRAY['Pelvis quieta','Espalda neutra','Extiende largo, no alto','Respira estable'], ARRAY['Girar cadera','Arquear espalda','Moverse rapido','Perder apoyo de manos'], ARRAY['Reducir rango si hay dolor lumbar','Usar solo piernas o solo brazos si falta control'], ARRAY['Dead bug','Plancha abdominal','Superman en suelo'], ARRAY['Pausas mas largas','Banda elastica','Mas reps por lado'], ARRAY['Solo pierna','Solo brazo','Rango corto'], 3, 10, 8, 12, 30, 60, 2, NULL, 'curado', NULL),
-- New row variants from the research coverage.
('sf-row-tbar', false, 'added_from_research', 'Remo en T', ARRAY['T-bar row','remo T','remo con barra T'], 'intermedio', 'intermedio', 'espalda', 'espalda media', ARRAY['dorsal ancho','romboides','trapecio medio','deltoides posterior','biceps','erectores espinales'], 'barra T, discos', ARRAY['barra T','discos'], 'gimnasio', 'hipertrofia', 'fuerza', 'jalon horizontal', 'Remo de espalda con barra T que permite cargar fuerte manteniendo un patron de jalon horizontal. Trabaja espalda media y dorsal con apoyo importante de estabilizadores.', ARRAY['Coloca discos en la barra o estacion T','Toma el agarre cerrado o amplio','Mantén torso firme y espalda neutra','Tira del agarre hacia abdomen o pecho bajo','Junta escapulas sin encoger hombros','Baja con control sin redondear espalda'], ARRAY['Pecho abierto','Codos hacia atras','Torso estable','Escapulas controladas'], ARRAY['Redondear espalda','Jalar con impulso','Encoger hombros','Recortar rango'], ARRAY['Evitar si provoca dolor lumbar','Usar remo pecho apoyado si cuesta estabilizar torso'], ARRAY['Remo con barra inclinado','Remo en polea sentado','Remo pecho apoyado'], ARRAY['Aumentar carga','Pausar arriba','Usar agarre amplio'], ARRAY['Remo en polea sentado','Remo con mancuerna a una mano'], 4, 10, 8, 12, 90, 150, 2, NULL, 'curado', NULL),
('sf-row-chest-supported', false, 'added_from_research', 'Remo pecho apoyado', ARRAY['chest-supported row','remo con pecho apoyado'], 'principiante', 'principiante', 'espalda', 'espalda media', ARRAY['dorsal ancho','romboides','trapecio medio','deltoides posterior','biceps'], 'banco inclinado, mancuernas', ARRAY['banco inclinado','mancuernas'], 'gimnasio', 'hipertrofia', 'fuerza', 'jalon horizontal', 'Remo con pecho apoyado que reduce impulso del torso y carga lumbar. Es util para aislar espalda media con tecnica controlada.', ARRAY['Ajusta banco inclinado y apoya el pecho','Toma las mancuernas con brazos extendidos','Jala codos hacia atras sin despegar el pecho','Pausa juntando escapulas','Baja lento hasta estirar espalda'], ARRAY['Pecho pegado al banco','Codos hacia atras','No encoger hombros','Controla la bajada'], ARRAY['Despegar pecho','Balancear mancuernas','Jalar solo con brazos','Usar carga excesiva'], ARRAY['Evitar si molesta el apoyo del pecho o hombros','Reducir inclinacion si incomoda'], ARRAY['Remo en polea sentado','Remo con mancuerna a una mano','Remo con barra inclinado'], ARRAY['Aumentar carga','Usar pausa arriba','Usar agarre neutro'], ARRAY['Remo en polea sentado','Remo con banda'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-curl-incline-db', false, 'added_from_research', 'Curl inclinado con mancuernas', ARRAY['incline dumbbell curl','curl inclinado'], 'intermedio', 'intermedio', 'brazos', 'biceps braquial cabeza larga', ARRAY['braquial','braquiorradial'], 'mancuernas, banco inclinado', ARRAY['mancuernas','banco inclinado'], 'gimnasio', 'hipertrofia', 'fuerza', 'curl de codo en estiramiento', 'Curl con brazos atras del torso que enfatiza la cabeza larga del biceps por mayor estiramiento inicial.', ARRAY['Ajusta banco inclinado','Sientate con espalda apoyada y brazos colgando','Flexiona codos sin adelantar hombros','Pausa arriba con control','Baja lento hasta estirar biceps'], ARRAY['Hombros atras','Codos quietos','Bajada lenta','Sin balanceo'], ARRAY['Adelantar codos','Usar impulso','Bajar demasiado rapido','Cargar mas de lo controlable'], ARRAY['Evitar si molesta hombro anterior o codo','Reducir rango si hay tiron excesivo'], ARRAY['Curl de bíceps con mancuernas','Curl de bíceps con barra','Curl predicador'], ARRAY['Aumentar carga','Tempo lento','Pausa en estiramiento controlado'], ARRAY['Curl alterno sentado','Curl en polea baja'], 3, 10, 10, 15, 60, 90, 2, NULL, 'curado', NULL),
('sf-curl-preacher', false, 'added_from_research', 'Curl predicador', ARRAY['preacher curl','curl en banco predicador'], 'intermedio', 'principiante', 'brazos', 'biceps braquial', ARRAY['braquial','braquiorradial'], 'banco predicador, barra EZ o mancuerna', ARRAY['banco predicador','barra EZ o mancuerna'], 'gimnasio', 'hipertrofia', 'fuerza', 'curl de codo apoyado', 'Curl con brazos apoyados que reduce trampa del torso y aisla el biceps con alto control.', ARRAY['Ajusta el banco para apoyar brazos completos','Toma barra EZ o mancuerna','Flexiona codos sin despegar brazos del soporte','Pausa arriba sin cerrar por completo','Baja lento sin bloquear codos con fuerza'], ARRAY['Brazos apoyados','Muñecas neutrales','Bajada lenta','Sin despegar hombros'], ARRAY['Rebotar abajo','Despegar brazos','Flexionar muñecas','Usar carga excesiva'], ARRAY['Evitar si molesta el codo en extension','No bloquees fuerte abajo'], ARRAY['Curl de bíceps con barra','Curl inclinado con mancuernas','Curl en polea baja'], ARRAY['Aumentar carga','Usar una mano','Pausar arriba'], ARRAY['Curl con mancuernas sentado','Curl en polea ligera'], 3, 10, 8, 12, 60, 90, 2, NULL, 'curado', NULL),
('sf-curl-concentration', false, 'added_from_research', 'Curl concentrado', ARRAY['concentration curl','curl de concentracion'], 'principiante', 'principiante', 'brazos', 'biceps braquial', ARRAY['braquial','antebrazo'], 'mancuerna, banco', ARRAY['mancuerna','banco'], 'cualquiera', 'hipertrofia', 'fuerza', 'curl de codo unilateral', 'Curl unilateral de aislamiento con apoyo del brazo en el muslo. Ayuda a controlar tecnica y sentir el biceps sin balanceo.', ARRAY['Sientate y apoya el brazo contra el muslo interno','Sostén mancuerna con palma hacia arriba','Flexiona el codo sin mover el hombro','Aprieta arriba brevemente','Baja lento hasta extension controlada'], ARRAY['Codo fijo','Movimiento lento','No gires torso','Control abajo'], ARRAY['Balancear hombro','Subir con impulso','Perder apoyo del brazo','Usar mucho peso'], ARRAY['Evitar si molesta codo o muñeca','Reducir carga'], ARRAY['Curl predicador','Curl de bíceps con mancuernas','Curl en polea baja'], ARRAY['Aumentar reps','Aumentar carga','Pausar arriba'], ARRAY['Curl alterno ligero','Curl con banda'], 3, 12, 10, 15, 45, 75, 2, NULL, 'curado', NULL),
('sf-curl-cable', false, 'added_from_research', 'Curl en polea baja', ARRAY['cable curl','curl en polea','low cable curl'], 'principiante', 'principiante', 'brazos', 'biceps braquial', ARRAY['braquial','braquiorradial'], 'polea baja, barra o cuerda', ARRAY['polea baja','barra o cuerda'], 'gimnasio', 'hipertrofia', 'fuerza', 'curl de codo en polea', 'Curl con polea baja que ofrece tension constante durante todo el recorrido. Es util para aislamiento y control.', ARRAY['Conecta barra o cuerda a polea baja','Ponte de pie con codos junto al torso','Flexiona codos manteniendo hombros quietos','Pausa arriba sin inclinarte','Regresa con control hasta extender brazos'], ARRAY['Codos fijos','Tension continua','Torso estable','No tires con espalda'], ARRAY['Balancear torso','Adelantar codos','Soltar la carga abajo','Usar peso excesivo'], ARRAY['Evitar si molesta codo o muñeca','Cambiar agarre si hay molestia'], ARRAY['Curl de bíceps con barra','Curl predicador','Curl inclinado con mancuernas'], ARRAY['Aumentar peso','Usar cuerda','Pausar en contraccion'], ARRAY['Reducir peso','Curl con banda','Curl con mancuernas ligero'], 3, 12, 10, 15, 45, 90, 2, NULL, 'curado', NULL),
('sf-curl-reverse-bar', false, 'added_from_research', 'Curl invertido con barra', ARRAY['reverse curl','barbell reverse curl'], 'intermedio', 'intermedio', 'brazos', 'braquiorradial', ARRAY['braquial','extensores de antebrazo','biceps braquial'], 'barra recta o barra EZ', ARRAY['barra recta o barra EZ'], 'gimnasio', 'hipertrofia', 'fuerza', 'curl de codo pronado', 'Curl con agarre prono que enfatiza braquiorradial y extensores de antebrazo. Complementa el trabajo de biceps y agarre.', ARRAY['Toma la barra con palmas hacia abajo','Mantén codos cerca del torso','Flexiona codos sin romper muñecas','Pausa arriba con control','Baja lento hasta extender brazos'], ARRAY['Muñecas rectas','Codos estables','Carga moderada','Bajada lenta'], ARRAY['Flexionar muñecas','Balancear torso','Usar mucho peso','Adelantar codos'], ARRAY['Evitar si causa dolor de muñeca','Usar barra EZ si molesta'], ARRAY['Curl martillo con mancuernas','Curl de bíceps con barra','Curl de muñeca con barra'], ARRAY['Aumentar carga gradualmente','Usar tempo lento','Pausar arriba'], ARRAY['Curl martillo ligero','Barra EZ ligera'], 3, 12, 10, 15, 45, 90, 2, NULL, 'curado', NULL),
('sf-triceps-pushdown', false, 'added_from_research', 'Pushdown de tríceps en polea', ARRAY['triceps pushdown','jalon de triceps en polea','pressdown'], 'principiante', 'principiante', 'brazos', 'triceps braquial', ARRAY['triceps lateral','triceps medial','antebrazo'], 'polea alta, cuerda o barra', ARRAY['polea alta','cuerda o barra'], 'gimnasio', 'hipertrofia', 'fuerza', 'extension de codo en polea', 'Extension de triceps en polea alta con tension constante. Es una variante segura y facil de dosificar para hipertrofia de triceps.', ARRAY['Conecta cuerda o barra a polea alta','Coloca codos cerca del torso','Extiende codos empujando el agarre hacia abajo','Contrae triceps al final','Regresa controlando sin mover hombros'], ARRAY['Codos fijos','Hombros quietos','Extiende completo','Controla regreso'], ARRAY['Separar codos','Inclinarse demasiado','Usar hombros','Soltar la carga arriba'], ARRAY['Evitar si causa dolor de codo','Cambiar agarre si molesta muñeca'], ARRAY['Extensión de tríceps por encima de la cabeza con mancuerna','Press francés con barra','Fondos en banco para tríceps'], ARRAY['Aumentar peso','Usar cuerda y abrir al final','Pausar abajo'], ARRAY['Menos carga','Banda elastica','Extension con mancuerna ligera'], 3, 12, 10, 15, 45, 90, 2, NULL, 'curado', NULL),
('sf-press-incline-db', false, 'added_from_research', 'Press inclinado con mancuernas', ARRAY['incline dumbbell press','press inclinado mancuernas'], 'principiante', 'principiante', 'pecho', 'pectoral superior', ARRAY['deltoides anterior','triceps'], 'mancuernas, banco inclinado', ARRAY['mancuernas','banco inclinado'], 'cualquiera', 'hipertrofia', 'fuerza', 'empuje horizontal inclinado', 'Press inclinado con mancuernas para pectoral superior, con mayor libertad de hombro que la barra.', ARRAY['Ajusta banco a inclinacion moderada','Sostén mancuernas a los lados del pecho','Retrae escapulas y apoya pies','Empuja mancuernas hacia arriba sin chocarlas','Baja con control manteniendo codos estables'], ARRAY['Escapulas firmes','Codos controlados','No choques mancuernas','Pies firmes'], ARRAY['Abrir codos de mas','Arquear espalda','Bajar sin control','Usar demasiado peso'], ARRAY['Evitar si causa dolor anterior de hombro','Reducir inclinacion o carga'], ARRAY['Press inclinado con barra','Press de banca con mancuernas','Lagartijas declinadas'], ARRAY['Aumentar carga','Pausar abajo','Tempo lento'], ARRAY['Press plano con mancuernas','Lagartijas inclinadas'], 3, 10, 8, 12, 90, 150, 2, NULL, 'curado', NULL),
('sf-chest-machine-press', false, 'added_from_research', 'Press en máquina de pecho', ARRAY['machine chest press','press de pecho en maquina'], 'principiante', 'principiante', 'pecho', 'pectoral mayor', ARRAY['triceps','deltoides anterior'], 'máquina de press de pecho', ARRAY['máquina de press de pecho'], 'gimnasio', 'hipertrofia', 'fuerza', 'empuje horizontal en maquina', 'Press guiado para pecho que permite entrenar empuje horizontal con alta estabilidad y facil ajuste de carga.', ARRAY['Ajusta asiento para que agarres queden a la altura del pecho','Apoya espalda y pies firmes','Empuja los agarres al frente sin bloquear con golpe','Pausa brevemente','Regresa con control hasta sentir estiramiento'], ARRAY['Espalda apoyada','Muñecas rectas','Controla regreso','No bloquees fuerte'], ARRAY['Ajustar asiento muy bajo','Encoger hombros','Rebotar la carga','Rango corto'], ARRAY['Evitar si la maquina obliga a dolor de hombro','Ajustar asiento o usar mancuernas'], ARRAY['Press de banca con mancuernas','Press de banca con barra','Lagartijas'], ARRAY['Aumentar carga','Pausar en estiramiento','Tempo lento'], ARRAY['Menor carga','Lagartijas inclinadas','Press con mancuernas ligero'], 3, 12, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-pushup-incline', false, 'added_from_research', 'Lagartijas inclinadas', ARRAY['incline push-up','flexiones inclinadas'], 'principiante', 'principiante', 'pecho', 'pectoral mayor', ARRAY['triceps','deltoides anterior','core'], 'banco o superficie elevada', ARRAY['banco o superficie elevada'], 'cualquiera', 'general', 'fuerza', 'empuje horizontal', 'Variante de lagartija con manos elevadas para reducir dificultad. Es ideal para principiantes o como regresion tecnica.', ARRAY['Coloca manos en una superficie estable','Extiende piernas y activa abdomen','Baja el pecho hacia la superficie','Mantén codos controlados','Empuja hasta volver a la posicion inicial'], ARRAY['Cuerpo en linea','Superficie estable','Codos controlados','Abdomen activo'], ARRAY['Hundir cadera','Abrir codos','Rebotar abajo','Superficie inestable'], ARRAY['Evitar si molesta muñeca u hombro','Elevar mas la superficie si falta fuerza'], ARRAY['Lagartijas','Press en máquina de pecho','Press de banca con mancuernas'], ARRAY['Bajar la altura','Agregar pausa','Pasar a lagartijas'], ARRAY['Mayor inclinacion','Apoyo de rodillas'], 3, 12, 8, 20, 45, 90, 2, NULL, 'curado', NULL),
('sf-pushup-decline', false, 'added_from_research', 'Lagartijas declinadas', ARRAY['decline push-up','flexiones declinadas'], 'intermedio', 'intermedio', 'pecho', 'pectoral superior', ARRAY['deltoides anterior','triceps','core'], 'banco o superficie elevada', ARRAY['banco o superficie elevada'], 'cualquiera', 'fuerza', 'fuerza', 'empuje horizontal declinado', 'Lagartija con pies elevados que aumenta demanda sobre pectoral superior y hombro anterior.', ARRAY['Coloca pies sobre un banco estable','Ubica manos bajo hombros','Activa abdomen y gluteos','Baja el pecho con control','Empuja el suelo sin perder alineacion'], ARRAY['Cuerpo rigido','Pies estables','Controla hombros','No hundas cadera'], ARRAY['Arquear espalda','Bajar cabeza primero','Abrir codos de mas','Usar altura excesiva'], ARRAY['Evitar si causa dolor de hombro o muñeca','Usar lagartijas normales si falta control'], ARRAY['Press inclinado con mancuernas','Lagartijas','Press inclinado con barra'], ARRAY['Elevar mas pies','Agregar pausa','Usar lastre'], ARRAY['Lagartijas','Lagartijas inclinadas'], 3, 10, 8, 15, 60, 120, 2, NULL, 'curado', NULL),
('sf-shoulder-arnold-press', false, 'added_from_research', 'Arnold press', ARRAY['arnold press','press arnold'], 'intermedio', 'intermedio', 'hombros', 'deltoides anterior', ARRAY['deltoides lateral','triceps','manguito rotador'], 'mancuernas', ARRAY['mancuernas'], 'cualquiera', 'hipertrofia', 'fuerza', 'empuje vertical con rotacion', 'Press con mancuernas que combina rotacion y empuje para trabajar deltoides anterior y lateral con gran rango.', ARRAY['Sientate o parate con mancuernas frente al pecho','Inicia con palmas hacia ti','Rota mientras empujas sobre la cabeza','Termina con control sin arquear espalda','Baja invirtiendo el recorrido'], ARRAY['Rotacion controlada','Costillas abajo','No choques mancuernas','Muñecas firmes'], ARRAY['Usar impulso','Arquear zona lumbar','Rotar sin control','Bajar demasiado rapido'], ARRAY['Evitar si provoca dolor de hombro','Usar press con mancuernas normal si molesta'], ARRAY['Press de hombro con mancuernas','Press militar con barra','Landmine press'], ARRAY['Aumentar carga','Pausa arriba','Tempo lento'], ARRAY['Press sentado con mancuernas','Landmine press'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-shoulder-landmine-press', false, 'added_from_research', 'Landmine press', ARRAY['landmine press','press landmine'], 'principiante', 'principiante', 'hombros', 'deltoides anterior', ARRAY['deltoides lateral','triceps','serrato anterior','core'], 'barra en landmine o esquina segura', ARRAY['barra','landmine o esquina segura'], 'gimnasio', 'fuerza', 'fuerza', 'empuje diagonal', 'Press diagonal con barra que suele ser mas amigable para hombros que un press vertical estricto.', ARRAY['Fija un extremo de la barra en landmine o esquina segura','Toma el extremo libre a la altura del hombro','Activa abdomen y gluteos','Empuja la barra en diagonal hacia arriba','Baja con control al hombro'], ARRAY['Trayectoria diagonal','Costillas abajo','Hombro estable','No gires tronco'], ARRAY['Arquear espalda','Empujar con impulso','Perder muñeca neutral','No fijar la barra'], ARRAY['Evitar si no puedes fijar la barra con seguridad','Reducir carga si molesta hombro'], ARRAY['Press de hombro con mancuernas','Press militar con barra','Arnold press'], ARRAY['Aumentar carga','Hacer unilateral','Pausar arriba'], ARRAY['Press con mancuerna ligera','Press sentado'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-shoulder-upright-row', false, 'added_from_research', 'Remo vertical con barra EZ', ARRAY['upright row','remo al menton','remo vertical'], 'intermedio', 'intermedio', 'hombros', 'deltoides lateral', ARRAY['trapecio superior','deltoides anterior','biceps'], 'barra EZ o mancuernas', ARRAY['barra EZ o mancuernas'], 'gimnasio', 'hipertrofia', 'fuerza', 'elevacion vertical', 'Elevacion vertical para deltoides lateral y trapecio. Debe hacerse con rango moderado y sin dolor de hombro.', ARRAY['Toma la barra con agarre comodo','Mantén la barra cerca del cuerpo','Eleva codos hasta altura tolerable','No subas si hay pinzamiento','Baja con control'], ARRAY['Codos guian','Rango sin dolor','Muñecas relajadas','Carga moderada'], ARRAY['Subir codos demasiado alto','Encoger cuello','Usar peso excesivo','Forzar dolor de hombro'], ARRAY['Evitar si provoca pinzamiento o dolor de hombro','Preferir elevaciones laterales si hay molestia'], ARRAY['Elevaciones laterales con mancuernas','Face pull en polea alta','Elevaciones laterales en polea'], ARRAY['Aumentar reps','Usar mancuernas','Tempo lento'], ARRAY['Elevaciones laterales ligeras','Face pull'], 3, 12, 10, 15, 45, 90, 2, NULL, 'revisar', NULL),
('sf-squat-bodyweight', false, 'added_from_research', 'Sentadilla con peso corporal', ARRAY['bodyweight squat','air squat'], 'principiante', 'principiante', 'piernas', 'cuadriceps', ARRAY['gluteo mayor','isquiosurales','aductores','core'], 'peso corporal', ARRAY['peso corporal'], 'cualquiera', 'general', 'fuerza', 'sentadilla', 'Sentadilla sin carga para aprender patron de rodilla y cadera. Es base para progresar a goblet, barra o prensa.', ARRAY['Coloca pies a anchura comoda','Activa abdomen y mira al frente','Desciende flexionando cadera y rodillas','Mantén rodillas alineadas con pies','Sube empujando el suelo'], ARRAY['Pie completo','Rodillas alineadas','Torso firme','Rango controlado'], ARRAY['Levantar talones','Colapsar rodillas','Perder postura','Rebotar abajo'], ARRAY['Reducir profundidad si hay dolor de rodilla o cadera'], ARRAY['Sentadilla goblet','Prensa de piernas','Zancadas con mancuernas'], ARRAY['Agregar reps','Usar pausa abajo','Pasar a goblet'], ARRAY['Sentadilla a caja','Rango parcial','Apoyo con manos'], 3, 15, 10, 20, 45, 90, 2, NULL, 'curado', NULL),
('sf-walking-lunges', false, 'added_from_research', 'Desplantes caminando', ARRAY['walking lunges','zancadas caminando'], 'intermedio', 'intermedio', 'piernas', 'cuadriceps', ARRAY['gluteo mayor','isquiosurales','aductores','core'], 'mancuernas opcionales', ARRAY['peso corporal','mancuernas opcionales'], 'cualquiera', 'hipertrofia', 'fuerza', 'zancada dinamica', 'Variante dinamica de zancada que entrena piernas, gluteos y estabilidad unilateral mientras se avanza.', ARRAY['Da un paso largo al frente','Baja controlando ambas rodillas','Mantén torso firme','Empuja el suelo con la pierna delantera','Avanza alternando piernas'], ARRAY['Paso controlado','Rodilla alineada','Torso estable','Empuja con talon'], ARRAY['Paso demasiado corto','Rodilla colapsa','Inclinar torso','Perder equilibrio'], ARRAY['Evitar si hay dolor de rodilla o inestabilidad','Usar zancadas estaticas como regresion'], ARRAY['Zancadas con mancuernas','Sentadilla búlgara con mancuernas','Step-ups'], ARRAY['Agregar mancuernas','Aumentar pasos','Pausa abajo'], ARRAY['Zancada estatica','Sentadilla goblet','Menos rango'], 3, 12, 10, 20, 60, 120, 2, NULL, 'curado', NULL),
('sf-step-ups', false, 'added_from_research', 'Step-ups', ARRAY['step up','subidas al banco'], 'principiante', 'principiante', 'piernas', 'cuadriceps', ARRAY['gluteo mayor','isquiosurales','core'], 'banco o caja estable', ARRAY['banco o caja estable'], 'cualquiera', 'general', 'fuerza', 'sentadilla unilateral', 'Subida a banco o caja que entrena fuerza unilateral de piernas y control de rodilla/cadera.', ARRAY['Coloca un pie completo sobre banco o caja','Inclina levemente el torso sin perder espalda neutra','Empuja con la pierna de arriba para subir','Controla la bajada sin dejarte caer','Alterna o completa reps por lado'], ARRAY['Pie completo arriba','Rodilla alineada','Sube sin impulso','Baja controlado'], ARRAY['Impulsarse con pierna de abajo','Usar caja demasiado alta','Colapsar rodilla','Caer al bajar'], ARRAY['Evitar si causa dolor de rodilla','Usar altura menor si falta control'], ARRAY['Sentadilla búlgara con mancuernas','Zancadas con mancuernas','Prensa de piernas'], ARRAY['Aumentar altura','Agregar mancuernas','Pausar arriba'], ARRAY['Altura menor','Apoyo con manos','Sentadilla goblet'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-rdl-single-leg-db', false, 'added_from_research', 'Peso muerto rumano a una pierna con mancuerna', ARRAY['single-leg rdl','single-leg dumbbell rdl'], 'intermedio', 'intermedio', 'piernas', 'isquiosurales', ARRAY['gluteo mayor','gluteo medio','core','estabilizadores de cadera'], 'mancuerna', ARRAY['mancuerna'], 'cualquiera', 'hipertrofia', 'fuerza', 'bisagra unilateral', 'Bisagra unilateral que trabaja isquiosurales y gluteos con alta demanda de equilibrio y estabilidad de cadera.', ARRAY['Sostén una mancuerna frente al muslo o contralateral','Apoya peso en una pierna con rodilla suave','Lleva cadera hacia atras elevando la pierna libre','Mantén pelvis cuadrada y espalda neutra','Regresa extendiendo cadera con control'], ARRAY['Pelvis estable','Cadera atras','Espalda neutra','Rango controlado'], ARRAY['Girar cadera','Redondear espalda','Perder equilibrio','Bajar sin control'], ARRAY['Evitar si hay dolor lumbar o mala estabilidad','Usar apoyo con mano libre'], ARRAY['Peso muerto rumano con mancuernas','Step-ups','Hip thrust con barra'], ARRAY['Aumentar carga','Pausa abajo','Menos apoyo externo'], ARRAY['Bisagra bilateral','Apoyo con pared','Rango corto'], 3, 10, 8, 12, 60, 120, 2, NULL, 'curado', NULL),
('sf-hamstring-ball-curl', false, 'added_from_research', 'Curl femoral con pelota', ARRAY['stability ball hamstring curl','curl femoral con fitball'], 'principiante', 'principiante', 'piernas', 'isquiosurales', ARRAY['gluteo mayor','core','gastrocnemio'], 'pelota de estabilidad', ARRAY['pelota de estabilidad'], 'cualquiera', 'general', 'fuerza', 'flexion de rodilla', 'Curl femoral en suelo con pelota que entrena isquiosurales y estabilidad de cadera sin maquina.', ARRAY['Acuestate boca arriba con talones sobre la pelota','Eleva cadera formando linea hombros-cadera-rodillas','Flexiona rodillas acercando la pelota','Mantén cadera alta','Extiende piernas con control'], ARRAY['Cadera alta','Talones presionan','Movimiento lento','Core activo'], ARRAY['Dejar caer cadera','Moverse rapido','Perder control de pelota','Arquear espalda'], ARRAY['Evitar si hay calambre fuerte o dolor lumbar','Reducir rango'], ARRAY['Curl femoral en máquina','Peso muerto rumano con mancuernas','Puente de gluteo'], ARRAY['Hacer a una pierna','Aumentar reps','Pausar flexionado'], ARRAY['Puente de gluteo','Rango parcial','Curl femoral en maquina ligero'], 3, 12, 10, 15, 45, 90, 2, NULL, 'curado', NULL),
('sf-cable-glute-kickback', false, 'added_from_research', 'Patada de glúteo en polea', ARRAY['cable glute kickback','glute kickback'], 'principiante', 'principiante', 'gluteos', 'gluteo mayor', ARRAY['isquiosurales','core','gluteo medio'], 'polea baja, tobillera', ARRAY['polea baja','tobillera'], 'gimnasio', 'hipertrofia', 'fuerza', 'extension de cadera', 'Aislamiento de gluteo mayor en polea baja con tension constante. Sirve como complemento a hip thrust y sentadillas.', ARRAY['Coloca tobillera en polea baja','Inclina ligeramente torso y sujeta soporte','Extiende la pierna hacia atras sin arquear espalda','Contrae gluteo al final','Regresa lento sin apoyar por completo'], ARRAY['Cadera estable','Movimiento desde gluteo','No arquees espalda','Controla regreso'], ARRAY['Patear con impulso','Girar cadera','Arquear lumbar','Usar demasiado peso'], ARRAY['Evitar si causa dolor lumbar','Reducir rango o carga'], ARRAY['Hip thrust con barra','Puente de glúteo con carga','Abducción de cadera con banda'], ARRAY['Aumentar carga','Pausar atras','Mas reps'], ARRAY['Puente de gluteo','Patada sin carga','Banda ligera'], 3, 15, 12, 20, 45, 90, 2, NULL, 'curado', NULL),
('sf-hip-abduction-band', false, 'added_from_research', 'Abducción de cadera con banda', ARRAY['band hip abduction','abducciones con banda'], 'principiante', 'principiante', 'gluteos', 'gluteo medio', ARRAY['gluteo menor','gluteo mayor','core'], 'banda elastica', ARRAY['banda elastica'], 'cualquiera', 'general', 'fuerza', 'abduccion de cadera', 'Ejercicio para gluteo medio y estabilidad lateral de cadera. Es util como accesorio o activacion antes de piernas.', ARRAY['Coloca banda sobre rodillas o tobillos','Mantén postura estable','Abre rodillas o pierna contra la banda','Pausa brevemente','Regresa controlando la tension'], ARRAY['Pelvis estable','Tension continua','No gires torso','Controla regreso'], ARRAY['Moverse con impulso','Perder tension de banda','Compensar con tronco','Rango excesivo'], ARRAY['Reducir tension si hay dolor de cadera'], ARRAY['Patada de glúteo en polea','Puente de glúteo','Step-ups'], ARRAY['Banda mas fuerte','Pausas mas largas','Mas reps'], ARRAY['Banda ligera','Menor rango','Sin banda'], 3, 20, 15, 25, 30, 60, 2, NULL, 'curado', NULL),
('sf-calf-seated', false, 'added_from_research', 'Elevación de talones sentado', ARRAY['seated calf raise','calf raise sentado'], 'principiante', 'principiante', 'piernas', 'soleo', ARRAY['gastrocnemio','estabilizadores de tobillo'], 'máquina o mancuerna sobre rodillas', ARRAY['máquina o mancuerna sobre rodillas'], 'gimnasio', 'hipertrofia', 'fuerza', 'flexion plantar sentado', 'Variante de pantorrilla con rodillas flexionadas que enfatiza el soleo.', ARRAY['Sientate con carga sobre rodillas o en maquina','Apoya la parte delantera de los pies','Eleva talones hasta contraer pantorrilla','Pausa arriba','Baja lento hasta estiramiento controlado'], ARRAY['Pausa arriba','Baja lento','No rebotes','Rodillas estables'], ARRAY['Rebotar','Rango corto','Usar demasiada carga','Perder apoyo del pie'], ARRAY['Evitar si hay dolor de tobillo o Aquiles'], ARRAY['Elevación de talones de pie con mancuernas','Elevación de talones en escalón','Elevación de talones en máquina'], ARRAY['Aumentar carga','Pausar arriba','Mas reps'], ARRAY['Peso corporal','Menor rango','Carga ligera'], 4, 15, 12, 20, 45, 90, 2, NULL, 'curado', NULL),
('sf-calf-step', false, 'added_from_research', 'Elevación de talones en escalón', ARRAY['step calf raise','calf raise on step'], 'principiante', 'principiante', 'piernas', 'gastrocnemio', ARRAY['soleo','estabilizadores de tobillo'], 'escalón o plataforma', ARRAY['escalón o plataforma'], 'cualquiera', 'hipertrofia', 'fuerza', 'flexion plantar en escalon', 'Elevacion de talones con mayor rango por el escalon. Permite estirar y contraer pantorrilla con control.', ARRAY['Coloca la parte delantera del pie en el escalon','Sujeta un apoyo si hace falta','Baja talones hasta estiramiento comodo','Sube lo mas alto posible','Pausa arriba y repite controlado'], ARRAY['Rango completo','Apoyo seguro','Pausa arriba','Bajada lenta'], ARRAY['Rebotar abajo','Perder equilibrio','No completar rango','Cargar demasiado pronto'], ARRAY['Evitar si hay dolor de Aquiles','Usar suelo plano como regresion'], ARRAY['Elevación de talones de pie con mancuernas','Elevación de talones sentado','Elevación de talones en máquina'], ARRAY['Agregar carga','Hacer unilateral','Pausas largas'], ARRAY['Suelo plano','Apoyo con manos','Peso corporal'], 4, 15, 12, 20, 45, 90, 2, NULL, 'curado', NULL),
('sf-forearm-farmer-walk', false, 'added_from_research', 'Caminata del granjero', ARRAY['farmer walk','farmers carry','farmer''s walk'], 'principiante', 'principiante', 'antebrazos', 'agarre', ARRAY['trapecio','core','antebrazos','gluteos'], 'mancuernas o kettlebells', ARRAY['mancuernas o kettlebells'], 'cualquiera', 'fuerza', 'fuerza', 'carga y agarre', 'Ejercicio de traslado cargado para agarre, antebrazos, trapecio y core. Muy util para fuerza funcional.', ARRAY['Toma dos cargas pesadas y seguras','Ponte de pie con postura alta','Camina pasos controlados sin inclinarte','Mantén hombros abajo y abdomen activo','Deja las cargas en el suelo con control'], ARRAY['Postura alta','Agarre firme','Pasos cortos','Core activo'], ARRAY['Inclinarse a un lado','Encoger hombros','Caminar demasiado rapido','Soltar sin control'], ARRAY['Evitar si hay dolor lumbar o de agarre','Usar carga menor'], ARRAY['Curl invertido con barra','Curl de muñeca con barra','Plancha abdominal'], ARRAY['Aumentar distancia','Aumentar carga','Usar una mano'], ARRAY['Menos carga','Menos distancia','Carga unilateral ligera'], 3, NULL, NULL, NULL, 60, 120, NULL, 30, 'curado', NULL),
('sf-forearm-wrist-curl-bar', false, 'added_from_research', 'Curl de muñeca con barra', ARRAY['barbell wrist curl','wrist curl'], 'principiante', 'principiante', 'antebrazos', 'flexores de muñeca', ARRAY['agarre','antebrazo'], 'barra recta o EZ', ARRAY['barra recta o EZ'], 'gimnasio', 'hipertrofia', 'fuerza', 'flexion de muñeca', 'Aislamiento para flexores de muñeca y antebrazo. Se usa con carga moderada y alto control.', ARRAY['Sientate y apoya antebrazos sobre muslos o banco','Toma barra con palmas hacia arriba','Deja que la muñeca baje con control','Flexiona muñecas elevando la barra','Baja lento sin perder agarre'], ARRAY['Antebrazos apoyados','Movimiento solo en muñeca','Carga ligera','Rango controlado'], ARRAY['Mover codos','Usar mucho peso','Rebotar abajo','Dolor de muñeca'], ARRAY['Evitar si hay dolor de muñeca','Usar mancuernas ligeras si molesta'], ARRAY['Curl invertido con barra','Curl inverso de muñeca','Caminata del granjero'], ARRAY['Aumentar reps','Pausar arriba','Aumentar carga ligera'], ARRAY['Menor carga','Mancuernas','Rango corto'], 3, 15, 12, 20, 45, 75, 2, NULL, 'curado', NULL),
('sf-forearm-reverse-wrist-curl', false, 'added_from_research', 'Curl inverso de muñeca', ARRAY['reverse wrist curl','extension de muñeca'], 'principiante', 'principiante', 'antebrazos', 'extensores de muñeca', ARRAY['antebrazo','agarre'], 'barra recta o mancuernas', ARRAY['barra recta o mancuernas'], 'gimnasio', 'hipertrofia', 'fuerza', 'extension de muñeca', 'Aislamiento para extensores de muñeca, util para equilibrar trabajo de antebrazo y agarre.', ARRAY['Apoya antebrazos sobre muslos o banco','Toma carga con palmas hacia abajo','Deja muñecas flexionar ligeramente','Extiende muñecas elevando la carga','Baja lento con control'], ARRAY['Carga ligera','Antebrazos quietos','Movimiento de muñeca','Control abajo'], ARRAY['Mover codos','Usar carga excesiva','Rango brusco','Dolor de muñeca'], ARRAY['Evitar si causa dolor de muñeca','Reducir carga'], ARRAY['Curl invertido con barra','Curl de muñeca con barra','Caminata del granjero'], ARRAY['Aumentar reps','Pausa arriba','Carga ligera progresiva'], ARRAY['Menor carga','Rango corto'], 3, 15, 12, 20, 45, 75, 2, NULL, 'curado', NULL),
('sf-core-dead-bug', false, 'added_from_research', 'Dead bug', ARRAY['dead bug','bicho muerto'], 'principiante', 'principiante', 'core', 'core', ARRAY['transverso abdominal','flexores de cadera','estabilidad lumbopelvica'], 'peso corporal', ARRAY['peso corporal'], 'cualquiera', 'general', 'core', 'anti-extension', 'Ejercicio de core anti-extension para controlar pelvis y zona lumbar mientras se mueven brazos y piernas.', ARRAY['Acuestate boca arriba con brazos arriba y rodillas a 90 grados','Presiona suavemente zona lumbar contra el suelo','Extiende brazo y pierna contraria sin arquear espalda','Regresa al centro con control','Alterna lados manteniendo respiracion'], ARRAY['Lumbar estable','Movimiento lento','Exhala al extender','No pierdas pelvis'], ARRAY['Arquear espalda','Moverse muy rapido','Bajar piernas demasiado','Contener respiracion'], ARRAY['Reducir rango si molesta lumbar','Mantener solo piernas si falta control'], ARRAY['Bird dog','Plancha abdominal','Hollow hold'], ARRAY['Extender mas bajo','Agregar pausa','Usar banda'], ARRAY['Menor rango','Solo brazos','Solo piernas'], 3, 10, 8, 12, 30, 60, 2, NULL, 'curado', NULL),
('sf-core-hollow-hold', false, 'added_from_research', 'Hollow hold', ARRAY['hollow body hold','hollow hold'], 'intermedio', 'intermedio', 'core', 'core', ARRAY['recto abdominal','transverso abdominal','flexores de cadera'], 'peso corporal', ARRAY['peso corporal'], 'cualquiera', 'general', 'core', 'anti-extension isometrica', 'Isometrico de core usado en calistenia para controlar posicion del tronco y pelvis. Es base para movimientos gimnasticos.', ARRAY['Acuestate boca arriba','Lleva costillas hacia pelvis y despega hombros','Extiende piernas segun tu nivel','Mantén zona lumbar cerca del suelo','Sostén el tiempo indicado respirando controlado'], ARRAY['Costillas abajo','Lumbar controlada','Piernas segun nivel','Respira corto y estable'], ARRAY['Arquear lumbar','Tensionar cuello','Bajar piernas demasiado','Contener respiracion'], ARRAY['Regresar a dead bug si hay dolor lumbar','Reducir palanca'], ARRAY['Plancha abdominal','Dead bug','L-sit'], ARRAY['Piernas mas bajas','Brazos extendidos','Mas tiempo'], ARRAY['Rodillas flexionadas','Dead bug','Menos tiempo'], 3, NULL, NULL, NULL, 45, 90, NULL, 30, 'curado', NULL);

-- Update existing rows from the catalog.
UPDATE public.exercises e
SET
  nombre = c.nombre,
  aliases = c.aliases,
  nivel = c.nivel,
  nivel_minimo = c.nivel_minimo,
  grupo_muscular = c.grupo_muscular,
  musculo_principal = c.musculo_principal,
  musculos_secundarios = c.musculos_secundarios,
  equipamiento = c.equipamiento,
  equipo_requerido = c.equipo_requerido,
  lugar = c.lugar,
  objetivo = c.objetivo,
  tipo_entrenamiento = c.tipo_entrenamiento,
  patron_movimiento = c.patron_movimiento,
  descripcion = c.descripcion,
  instrucciones = c.instrucciones,
  cues_tecnicos = c.cues_tecnicos,
  errores_comunes = c.errores_comunes,
  contraindicaciones = c.contraindicaciones,
  sustituciones = c.sustituciones,
  progresiones = c.progresiones,
  regresiones = c.regresiones,
  series_sugeridas = c.series_sugeridas,
  repeticiones_sugeridas = c.repeticiones_sugeridas,
  rango_reps_min = c.rango_reps_min,
  rango_reps_max = c.rango_reps_max,
  descanso_segundos_min = c.descanso_segundos_min,
  descanso_segundos_max = c.descanso_segundos_max,
  rir_recomendado = c.rir_recomendado,
  duracion_promedio_segundos = c.duracion_promedio_segundos,
  estado_calidad = c.estado_calidad
FROM sprint613_exercise_catalog c
WHERE e.id = c.id
  AND c.existed_before = true;

-- Insert new professional variants.
INSERT INTO public.exercises (
  id, nombre, aliases, nivel, nivel_minimo, grupo_muscular, musculo_principal,
  musculos_secundarios, equipamiento, equipo_requerido, lugar, objetivo,
  tipo_entrenamiento, patron_movimiento, descripcion, instrucciones, cues_tecnicos,
  errores_comunes, contraindicaciones, sustituciones, progresiones, regresiones,
  series_sugeridas, repeticiones_sugeridas, rango_reps_min, rango_reps_max,
  descanso_segundos_min, descanso_segundos_max, rir_recomendado,
  duracion_promedio_segundos, estado_calidad, imagen, video
)
SELECT
  id, nombre, aliases, nivel, nivel_minimo, grupo_muscular, musculo_principal,
  musculos_secundarios, equipamiento, equipo_requerido, lugar, objetivo,
  tipo_entrenamiento, patron_movimiento, descripcion, instrucciones, cues_tecnicos,
  errores_comunes, contraindicaciones, sustituciones, progresiones, regresiones,
  series_sugeridas, repeticiones_sugeridas, rango_reps_min, rango_reps_max,
  descanso_segundos_min, descanso_segundos_max, rir_recomendado,
  duracion_promedio_segundos, estado_calidad, NULL, NULL
FROM sprint613_exercise_catalog
WHERE existed_before = false
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  aliases = EXCLUDED.aliases,
  nivel = EXCLUDED.nivel,
  nivel_minimo = EXCLUDED.nivel_minimo,
  grupo_muscular = EXCLUDED.grupo_muscular,
  musculo_principal = EXCLUDED.musculo_principal,
  musculos_secundarios = EXCLUDED.musculos_secundarios,
  equipamiento = EXCLUDED.equipamiento,
  equipo_requerido = EXCLUDED.equipo_requerido,
  lugar = EXCLUDED.lugar,
  objetivo = EXCLUDED.objetivo,
  tipo_entrenamiento = EXCLUDED.tipo_entrenamiento,
  patron_movimiento = EXCLUDED.patron_movimiento,
  descripcion = EXCLUDED.descripcion,
  instrucciones = EXCLUDED.instrucciones,
  cues_tecnicos = EXCLUDED.cues_tecnicos,
  errores_comunes = EXCLUDED.errores_comunes,
  contraindicaciones = EXCLUDED.contraindicaciones,
  sustituciones = EXCLUDED.sustituciones,
  progresiones = EXCLUDED.progresiones,
  regresiones = EXCLUDED.regresiones,
  series_sugeridas = EXCLUDED.series_sugeridas,
  repeticiones_sugeridas = EXCLUDED.repeticiones_sugeridas,
  rango_reps_min = EXCLUDED.rango_reps_min,
  rango_reps_max = EXCLUDED.rango_reps_max,
  descanso_segundos_min = EXCLUDED.descanso_segundos_min,
  descanso_segundos_max = EXCLUDED.descanso_segundos_max,
  rir_recomendado = EXCLUDED.rir_recomendado,
  duracion_promedio_segundos = EXCLUDED.duracion_promedio_segundos,
  estado_calidad = EXCLUDED.estado_calidad;

-- Remove accidental self-substitutions and duplicates while preserving order.
UPDATE public.exercises e
SET sustituciones = cleaned.items
FROM (
  SELECT
    id,
    COALESCE(array_agg(item ORDER BY first_seen) FILTER (WHERE item IS NOT NULL), '{}'::text[]) AS items
  FROM (
    SELECT
      e.id,
      s.item,
      min(s.ordinality) AS first_seen
    FROM public.exercises e
    LEFT JOIN LATERAL unnest(e.sustituciones) WITH ORDINALITY AS s(item, ordinality) ON true
    WHERE s.item IS NULL
       OR (
        lower(trim(s.item)) <> lower(trim(e.nombre))
        AND lower(trim(s.item)) <> ALL (
          SELECT lower(trim(alias_item))
          FROM unnest(e.aliases) AS alias_item
        )
      )
    GROUP BY e.id, s.item
  ) deduped
  GROUP BY id
) cleaned
WHERE e.id = cleaned.id;

-- Cardio uses duration instead of strength reps/RIR.
UPDATE public.exercises
SET rango_reps_min = NULL,
    rango_reps_max = NULL,
    rir_recomendado = NULL
WHERE tipo_entrenamiento ILIKE 'cardio%';

COMMENT ON COLUMN public.exercises.instrucciones IS
  'Step-by-step exercise execution instructions. Added for Sprint 6.1.3 professional exercise library.';

